### ISSUE TITLE
State changes

### ISSUE THREAD

**Issue by aemadrid** [clearwater-rb/clearwater#17]
How do you handle state changes that affect rendered views? Say given the example on the Readme page you get a notification that an article changed or was added (e.g. from Pusher). How do you update the @articles and make the page rerender?

**Comment by jgaskins** [comment]
This is something we'll have to work on at the data store level, I think. One of the things I've been experimenting with for rerendering on model updates:

```ruby
article_store = Store.new(Article, '/api/v1/articles') # Some hypothetical object to map models to the API
article_store.on :fetch_all do |articles| # yield fetched models
  MyApp.render # Rerender because we have new data
end
```

Since you mentioned Pusher updates specifically, it might go something like this:

```ruby
pusher_channel = pusher.bind("articles")
pusher_channel.bind 'update' do |data|
  model = article_store.find(data[:id])
  model.set_attributes data[:article]

  MyApp.render
end
```

Speaking of which, I've got Opal bindings for Pusher (we use it heavily at work) I'll publish when I have some free time.

**Comment by aemadrid** [comment]
Interesting. So we handle the rerendering on the store. For some reason I was expecting to cahnge the store and the app to figure out how to rerender itself without doing all the thinking. Meaning rerendering only the affected parts. Does React rerender (rethink) the whole app too?

**Comment by aemadrid** [comment]
I guess to answer my own question here is something that makes it clear how react does this: http://jsbin.com/xozesunudi/1/edit?js,output

In short it seems react does the same thing although it provides a way to decide at the component level if it should rerender itself. Maybe that is worth looking at in CW?

**Comment by jgaskins** [comment]
In order to trigger a rerender on specific components, our usage of the virtual DOM will need a bit more work. The [`virtual-dom` library](https://github.com/Matt-Esch/virtual-dom) we're using supports a lot of optimizations, but Clearwater's bindings to it are still primitive; we're only using the four basic operations: generating virtual DOM nodes, diffing, patching, and converting virtual DOM nodes to real DOM nodes.

In #10, one of the bullet points was to try to add support for more of those operations, but most JS frameworks that have been around a lot longer still don't use a virtual DOM and, to my knowledge, Clearwater is the first of the Opal frameworks to use one. So even though it's triggering a render on the entire app vs individual components, it's not _actually_ rerendering the whole thing. I want to see performance bottlenecks in larger, more complicated apps before I try to optimize too much, because a lot of the optimizations I have in mind involve tradeoffs (such as memory consumption vs execution time).

On the topic of optional rendering (a la React's `shouldComponentUpdate`), I added #15 for that last weekend.

> So we handle the rerendering on the store.

The store would simply execute a callback. What happens inside that callback is outside the responsibility of the store. See [inversion of control](http://en.wikipedia.org/wiki/Inversion_of_control).

> For some reason I was expecting to cahnge the store and the app to figure out how to rerender itself without doing all the thinking.

For that to happen, we would need to implement the observer pattern on both stores and `Application`. This pattern isn't bad, but it doesn't _really_ change the code you write.

Instead of this:

```ruby
store.on :fetch do
  MyApp.render
end
```

… where all of the code is self-contained, you would instead write something like this:

```ruby
MyApp.observe store, :fetch do
  MyApp.render
end
```

Then when the store performs an action, it calls `notify` on everything that has registered as an observer. This is functionally equivalent, requires similar code from the outside, but actually adds internal complexity.

Here's how you might implement the simple event:

```ruby
class Store
  # ...

  def on event, &block
    event_handlers[event] << block
  end

  def fetch_all
    data = go_get_the_data
    event_handlers[:fetch_all].each { |handler| handler.call data }
  end
end
```

That's basically it. All you need is to ensure that event_handlers returns a modifiable `Enumerable` for any key passed in. For the observer, it's a bit more complicated:

```ruby
class Store
  def register_observer observer, channel
    observers[channel] << observer
  end

  def fetch_all
    observers[:fetch_all].each { |observer| observer.notify(self, :fetch_all) }
  end
end

class Application
  def observe observable, channel
    observable.register_observer self, channel
  end

  def notify observable, channel
    render
  end
end
```

Both of these examples are kinda primitive, but they would probably work. I'm not sure how I feel about observing vs plain events because I don't see the observer pattern used much, but I like that events are simpler and involve fewer dependencies.

**Comment by aemadrid** [comment]
Thanks for taking the time to respond with so much detail. The options you present are clear and make sense to me. On #15 I'm guessing that you were targeting caching static content but I'm more concerned with dealing with lots of smaller objects. But I can see that the component could be smarter and digest what it should show itself and be smart about it (immutable objects, smart filtering, etc).

**Comment by jgaskins** [comment]
I've been thinking about this a lot more lately and I might implement a store similar to [Redux](https://github.com/rackt/redux), where you have one app-wide store to which you dispatch actions. When you instantiate the store, you pass in the initial state and a block that yields the current state and the action you dispatched and returns the new value of the state:

```ruby
store = Store.new(initial_state) do |state, action|
  # compute and return new state here
end
```

You dispatch action objects which have some data associated with them. This data might be a new chat message pulled in from Pusher:

```ruby
store.dispatch Actions::NewComment.new(comment)
```

Then when the store receives that dispatch, it checks the type of action and computes new state based on the current state and that action:

```ruby
store = Store.new(comments: []) do |state, action|
  case action
  when Actions::NewComment
    state.merge comments: state[:comments] + [action.comment]
  # Always return the current state if there isn't a handler for the action
  else
    state
  end
end

store.on_dispatch do |old_state, new_state|
  app.render unless old_state.equal?(new_state)
end
```

You can see in the `on_dispatch` block that we rerender the app if the *identity* of the store's `state` hash changes. Since this is an identity comparison, it happens in O(1) time, no matter how much state your application has.

If you mutate the original state (because that is faster than returning a new object with minor modifications), you need to check equivalence instead of identity to see if anything changed, which is O(n), at which point you've consumed almost the same amount of processing time as copying the state object to begin with. When you consider that applications read state more frequently than write to it, copying the state to a new object is actually *cheaper* in the long run, especially where it matters the most (rendering).

This will also help if someone is using the `Clearwater::CachedRender` mixin in their components:

```ruby
CommentsList = Struct.new(:store) do
  include Clearwater::Component
  include Clearwater::CachedRender

  def render
    @old_state = comments

    div(attributes, content)
  end

  def should_render?
    @old_state.equal? comments
  end

  def comments
    store.state[:comments]
  end
end
```

**Comment by jgaskins** [comment]
I think I'm going to go ahead and close this one. I did end up implementing the store I mentioned above and published it as the [`grand_central`](https://github.com/clearwater-rb/grand_central) gem.
