### ISSUE TITLE
Clearwater::Component needs to give more reflection

### ISSUE THREAD

**Issue by krainboltgreene** [clearwater-rb/clearwater#25]
I was attempting to do a little fun stuff tonight by mimicking the React "css-modules" and I found a surprising lack of reflection for the thing that represents a DOM element. I don't know if it's the VirtualDOM layer or whatever, but I'd love to be able to recursively do things down the tree.

**Comment by krainboltgreene** [comment]
Specifically I wanted to collect my current tree's `style` property, so I could create a CSS stylesheet.

**Comment by jgaskins** [comment]
Originally, we had `VirtualDOM::Node` objects that wrapped their JS counterparts, but after a lot of refactoring, they were nothing more than POROs with a single `attr_reader` so I removed them entirely to get rid of the overhead of allocating and initializing potentially several thousand objects per render.

The truth is, I haven't actually needed to look into virtual-dom nodes. Because they're a byproduct of component state, I can't think of anything in the generated node that your component doesn't have access to.
