### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by jegt** [clearwater-rb/clearwater#29]
We're in the process of converting our app to use clearwater and one of the problems we have found is our svg icons. We used to embed them using SVGInjector which doesn't work with virtual-dom. 

There seem to be some support for svg in virtual-dom/virtual-hyperscript/svg.js but as far as I can see it's not included into clearwater. 

If it was included I could write a svg() method for the DSL that reads the svg xml and embeds it in the vtree. Does that sound like the right way to approach this?

**Comment by jgaskins** [comment]
@jegt That sounds pretty good. I'd actually wondered about virtual-dom's SVG and `canvas` support, but to be honest I don't know enough about either one to even know where to look. That part of virtual-hyperscript is a good starting point for me, though. I'll check this out. :-)

**Comment by jegt** [comment]
I have been exploring this a bit in a fork: https://github.com/arkivdigital/clearwater

Right now I'm working on a solution for reading the svg files and compiling them to ruby code that generates vtrees for each svg. But that might be specific for our use case.

**Comment by jgaskins** [comment]
I was thinking of compiling virtual-dom's SVG support into a separate vendored JS file (so SVG isn't loaded by default), but I think that will take some extra work because of [the other UMD requires](https://github.com/Matt-Esch/virtual-dom/blob/903d884a8e4f05f303ec6f2b920a3b5237cf8b92/virtual-hyperscript/svg.js#L3-L9) the SVG module pulls in. Since most of these things are already loaded in `virtual-dom`, we don't want to load a duplicate implementation of them and I don't know of a way to wire it up without duplication yet using Sprockets.

Then again, if SVG support makes very little difference in payload size, maybe we could just add it in by default and not have to worry about trying to make Sprockets and UMD play nicely together. I just need to play with it, really.

**Comment by jgaskins** [comment]
… aaaaand that's kinda what you did and I think I like it.

**Comment by jgaskins** [comment]
When it comes to the SVG commands, though, we'll need to add support for that as well. The problem is that `a` is both an SVG command and an HTML element. So what if we had a `SVGComponent` mixin (or something similar) to avoid naming collisions? For this example SVG node:

```xml
<svg viewBox="0 0 120 120" version="1.1" xmlns="http://www.w3.org/2000/svg">
  <circle cx="60" cy="60" r="50"/>
</svg>
```

Could be included into an application like this:

```ruby
class MySVGContainer
  include Clearwater::Component

  def render
    # SVG container goes into a parent component
    svg({ view_box: '0 0 120 120' }, [
      # SVG content is defined in other components
      FrigginSweetCircle.new,
    ])
  end
end

class FrigginSweetCircle
  include Clearwater::SVGComponent

  def render
    circle(cx: 60, cy: 60, r: 50)
  end
end
```

**Comment by jegt** [comment]
Yes a SVGComponent sounds like a good idea. 

I'm currently working on my svg to ruby compiler but let me know if there is anything I can do to help.

**Comment by jgaskins** [comment]
Cool, if that makes sense for your use case, it might work for others. I'll try and knock something out for it so you can test it out.
