### ISSUE TITLE
Can't get the example app from the readme to work.

### ISSUE THREAD

**Issue by jakeonrails** [clearwater-rb/clearwater#38]
Here's what I did:

gem install clearwater

copied the Example App from README.md into a new file `example.rb`

add `require 'clearwater'` to the top of that new file

run `ruby example.rb`

output:

```
example.rb:4:in `<class:Layout>': uninitialized constant Clearwater::Component (NameError)
	from example.rb:3:in `<main>'
```

The first four lines:

```ruby
require 'clearwater'

class Layout
  include Clearwater::Component
```

What am I doing wrong here? I tried reading the requires inside of the gem itself but it appears that `lib/clearwater.rb` doesn't actually do anything to require it's own source code. It seems to add another file to the Opal load path but I don't see how that will actually require the relevant code.

I tried `require 'opal'` as in the Rails app example but that did not work either.

I feel like I'm missing something here.

**Comment by jgaskins** [comment]
Are you trying to run the Clearwater app with MRI? If so, that won't work. :-) That could probably be emphasized on the readme. It does mention a "standalone" app, but that's misleading. I just don't know of a word that means "an app whose dependencies are not managed by Bundler". :-)

In the ["Using with Rails"](https://github.com/clearwater-rb/clearwater#using-with-rails) section, it shows that you put your Clearwater code into `app/assets/javascripts/application.rb`. So that's where you need to put that code in a Rails app.

**Comment by jakeonrails** [comment]
Yes I tried running it with MRI ruby. 

From your comment I'm guessing I need to use Opal to run it?

I ran `opal --compile example.rb > example.js`, and then I made this html file:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script src="example.js"></script>
  </head>
  <body>
  </body>
</html>
```

But when I open that in Chrome, nothing happens, and the console doesn't show any errors or issues. `example.js` loads, and I can see about 15k lines of javascript in there.

But no articles.

**Comment by jgaskins** [comment]
@jakeonrails A couple things:

That example Clearwater app is meant to be run within a Rails app, rather than loading from the filesystem. The good news is that you can still run it that way. :-) If you put `require 'ostruct'` at the top of the file (I really should've put those requires in the readme, tbh) with the other requires and move the `script` tag inside the `body` tag, it'll run:

```ruby
# Top of example.rb
require 'opal'
require 'clearwater'
require 'ostruct'
```

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <script src="example.js"></script>
  </body>
</html>
```

The bad news is that you won't be able to take advantage of Clearwater routing while loading from the filesystem, which the blog part of that app depends on.

**Comment by jgaskins** [comment]
The reason you need to put the `script` within the `body` is that if you don't, the `body` element doesn't exist when the program is executed:
 
![screen shot 2016-03-03 at 4 30 33 pm](https://cloud.githubusercontent.com/assets/108205/13510161/554327b0-e15d-11e5-92ce-9d7149200abe.png)

This is usually handled in apps using jQuery or similar by hooking into the `document.ready` event. There isn't yet an equivalent in [`bowser`](https://github.com/clearwater-rb/bowser), the DOM abstraction used in Clearwater, because the [simplest cross-browser way to do it](http://stackoverflow.com/a/9899701) is gross. :-\ So putting your script tag at the end of the `body` is the best way to do it currently.

**Comment by jakeonrails** [comment]
Ah that makes a ton of sense. So I moved my script to the body tag, and now I get an error in the console that `Clearwater::Layout` cannot be found. I tried adding `require "clearwater"` back to the ruby file but Opal complains that it can't find the file. So next I created a Gemfile, added clearwater and opal to it, and then compiled using `bundle exec opal example.rb > example.js` and still get the same error in the JS console w/ or w/out the `require 'clearwater'` statement in the ruby file.

Thanks again for all your help! I'm really intrigued w/ clearwater; I read about it in an article today comparing it to turbolinks.

**Comment by jakeonrails** [comment]
Woops, I didn't see you made a second comment - let me try what you have there.

**Comment by jgaskins** [comment]
I couldn't get it to compile using that `opal` command. Here's how I ran it:

```
ruby -rclearwater -ropal -S opal -c example.rb > example.js
```

That loads the `clearwater` and `opal` gems in MRI, then runs `opal` to do the compilation.

**Comment by jgaskins** [comment]
I just realized you can wrap the app instantiation/rendering in a `Bowser.window.animation_frame` block to defer it until after the body is loaded:

```ruby
Bowser.window.animation_frame do
  MyApp = Clearwater::Application.new(
    component: Layout.new,
    router: router,
    element: Bowser.document.body # This is the default target element
  )

  MyApp.call # Render the app.
end
```

This works because `Bowser.window.animation_frame` hooks into the browser's event loop rather than executing immediately because it's backed by `requestAnimationFrame` (falling back to `setTimeout` if the browser does not support `requestAnimationFrame`). The async execution there allows the HTML to finish rendering before running your app.

It's just like using `async` or `defer` attributes on the `script` tag, which would also work here. Just don't use them in the Rails development environment unless you concatenate assets or your dependencies are unlikely to load in order. :-)

**Comment by jgaskins** [comment]
Gonna go ahead and close this since I've verified you can run a Clearwater app this way. :-)
