### ISSUE TITLE
Clean up router code

### ISSUE THREAD

**Issue by jgaskins** [clearwater-rb/clearwater#4]
Some of the methods in the [router](https://github.com/jgaskins/clearwater/blob/master/opal/clearwater/router.rb) that are used internally may be inefficient. I'm not exactly sure of the dependency structure of the methods inside that class, but I don't feel confident that we're only generating the same data once for the same path.

This is mainly a note to myself to check this out, but if someone else can have a look, that'd be fine, too.

**Comment by krainboltgreene** [comment]
I'm about to ship my gem earhart, which is a pure ruby HTTP routing library. I'm going to test it out in a branch at some point.

**Comment by jgaskins** [comment]
When you say "HTTP routing", do you mean server-side routing? I ask because client-side routing is a bit different due to not having HTTP verbs.

**Comment by krainboltgreene** [comment]
You don't implicity have verbs, but you *can*. It just becomes part of the
URI.

**Comment by jgaskins** [comment]
I don't understand what you mean. Can you talk a bit about how it works?

**Comment by krainboltgreene** [comment]
Basically I wanted a fast reliable and pure ruby routing library. The way I built it is it takes an identifier: `GET http://api.example.com/accounts/1` and essentially uses that to lookup on a complex dictionary where keys are patterns.

This works great for a standard HTTP library, obviously. The reason verbs exist are to provide a common set of vocabulary for clients & servers. Clients don't *need* that common vocabulary, due to it really just talking to itself, but you can still use this as listen/notify key. `GET http://app.example.com/accounts/1` simply becomes the key for `Clearwater::Control::Show`.

Benefits:

  1. `<a>` links still work, even if the javascript fails. (Also bots)
  2. If we have to act as a proxy to a third party in the client there's no extra work.
