### ISSUE TITLE
Document the need for virtual dom

### ISSUE THREAD

**Issue by dancinglightning** [clearwater-rb/clearwater#54]
Reading all about clearwater it looks really very very good. Not doubt. And it seems to be in real use, which is encouraging.

The only thing that quirks me, to the degree that i haven't taking clearwater for a ride yet, is the vdom.
I just can't seem to understand what is wrong with the simple / vienna approach of just keeping the elements around and changing them when needed.

The best i found is that "dom manipulation is messy" , which i don't see. Dom as a clear api and extending that to components is not difficult. There is really only add/remove/edit you can do.
Also i found that "keeping track of state is hard" , but seems to me what programs do, keeping track of state, and so holding on to previously created instances doesn't seem to hard.

So i'm just putting this here in the hope i may not be the only one not getting it. And maybe I can assist in creating a paragraph or two or a wiki page.

**Comment by jgaskins** [comment]
I'll see what I can do. :-) Here goes:

A virtual DOM gives 3 main benefits over traditional DOM manipulation:

1. Declarative UI
2. Guaranteed only one page reflow per render for nearly everything
3. Easy event handling

## Declarative UI

> The best i found is that "dom manipulation is messy" , which i don't see.

It _can_ be. For some apps, it's perfectly fine.

One of the hardest things about some UIs is transitioning between app states. If you're manipulating the DOM on your own, you have to write your own code for that transition. If you can transition from both state A and B to state C (for example, if you can checkout from both a cart and from a buy-now button in an ecommerce app), you have to write code to handle both transitions — taking away existing DOM nodes and adding others is probably a different process depending on whether you're coming from A or B.

In all cases, though, a virtual DOM is declarative. You only need to specify what it needs to look like. You can go from any state to any state in a single line of code (in the case of a Clearwater app: `app.render`). This is extremely helpful if your app updates in real time over a websocket and multiple updates come in between renders. One render pass and it's up to date.

## Single Page Reflow

Page reflows are necessary for rendering. If they never happen, your UI will never update. However, they're slow, so the optimal number of reflows per render is 1.

Rendering via DOM manipulation in something like Backbone usually triggers page a reflow for _each view_. Each view has to find its container in the DOM and render its template into it. That's a read/write for every single view throughout your entire rendering process. If you're only updating a single view that has no child views, that's not such a big deal, but if you're updating a large container view with a wide or deep tree of descendants, you can easily trigger 100 reflows in a single render.

A virtual DOM guarantees a single reflow per render, no matter how complex your UI is. These generally happen in 50-100ms even on slow devices for apps whose UIs aren't overly complicated, so if your UI updates primarily through a user clicking through the app, you can probably get away with the performance of interleaved reads/writes.

## Event Handling Context

If you assign event handlers during render with things like `onclick`, for example, you can use the component as the context for the handler and all event handlers for that particular DOM node are right there for you to see. You don't have to go searching through a separate piece of code to see where all the handlers are.

This is a tradeoff, though, because sometimes it's also nice to see all your event handlers in one place. I've never missed that, to be honest, but it was a nice perk sometimes. I actually prefer the `onclick` way after using it for a while.

**Comment by dancinglightning** [comment]
@jgaskins that was definitely more than i bargained for, and quick. Great answer.

This has answered my question and i would make a wiki page out of your reply, ok?
So your effort doesn't go to waste.

I am tempted to ask questions, but then maybe i should go on gitter.

**Comment by jgaskins** [comment]
> This has answered my question and i would make a wiki page out of your reply, ok?

That would be fantastic!

To be honest, I've answered a lot of questions on Gitter that would probably be great as wiki pages. The ephemeral nature of a chat app means that we'll probably lose those if we don't do something with them before too long.

I'm working on a documentation site, as well, so I might incorporate some of these things there, too. I just need to stop dragging my feet on it and just push some code out. ;-)

**Comment by dancinglightning** [comment]
Ok, done the wiki.

I can help a little with a doc site, i've done some github pages with jekyll. 
if  you want. I'll hang in gitter for a little
