### ISSUE TITLE
move atrributes/content argument handling to #Component#tag

### ISSUE THREAD

**Issue by balmoral** [clearwater-rb/clearwater#65]
Currently the methods defined for HTML_TAGS in Component inspect attributes/content arguments before passing to Component#tag.

Moving the argument handling code to Component#tag allows use of the #tag method with safe argument handling.. 

```
   HTML_TAGS.each do |tag_name|
      define_method(tag_name) do |attributes, content|
        tag(tag_name, attributes, content)
      end
    end

    def tag tag_name, attributes=nil, content=nil
      %x{
        if(!(attributes === nil || attributes.$$is_hash)) {
          content = attributes;
          attributes = nil;
        }
      }
      VirtualDOM.node(
        tag_name,
        Component.sanitize_attributes(attributes),
        Component.sanitize_content(content)
      )
    end
```

**Comment by jgaskins** [comment]
It used to be in `tag`, actually. :-) I moved it for performance reasons. Because all of the `HTML_TAGS` methods funnel through it, the many varied ways people call them were causing a large combination of function signatures:

| Signature                   | Example
|-----------------------------|---------------------------------------------------------------|
| `tag(String, Object, Array)`| `div({ class_name: 'foo' }, [ ... ])`                         |
| `tag(String, Array)`        | `div([ ... ])`                                                |
| `tag(String)`               | `br`                                                          |
| `tag(String, Object)`       | `input(oninput: method(:set_text))`                           |
| `tag(String, Object, String)`| `button({ onclick: method(:clicked!) }, 'Click me')`          |
| `tag(String, String)`       | `h1(page.title)`                                              |
| `tag(String, Number)`       | `span(click_count)`                                           |
| `tag(String, Object, Object)`| `div({ class_name: 'foo' }, MyComponent.new)`                 |
| `tag(String, Object)`       | `div(MyComponent.new)`                                        |

There may be more. This is just what I could think of off the top of my head. The problem this causes is that `tag` then has too many different function signatures for the VM to optimize and it will bail on optimizing — Chrome's V8 calls this deoptimization "Optimized too many times". The VM stops after a certain point to save on RAM and the CPU cost of running optimizations. This makes every call into the tag DSL slower.

By pulling that sanitization outside of `tag` and into each of the tag methods (tag methods being `div`, `span`, and friends), we reduce the number of optimized function signatures for `tag` below the deoptimization threshold:

| Signature                   | Example
|-----------------------------|---------------------------------------------------------------|
| `tag(String, Object, Array)`  | `tag(:div, { class_name: 'foo' }, [ ... ])`                         |
| `tag(String, Object, String)` | `tag(:div, { onclick: method(:clicked!) }, 'Click me')`          |
| `tag(String, Object, Number)` | `tag(:span, nil, click_count)`          |
| `tag(String, Object, Object)` | `tag(:div, nil, MyComponent.new)`                 |

 This won't stop the other tag methods from deoptimizing, of course, but if `div` is the only function that gets deoptimized while the rest stay fast, the overall performance of rendering is higher.

**Comment by balmoral** [comment]
Trickier than it looks. :-)

Thought it too obvious for you to miss, and didn't consider performance hit. 

Thanks for the detailed explanation.

I guess I can use #send instead of #tag and get the same result (I've got a grid/table generator which allows any component in a cell, and was passing the component type through to #tag) - do you know if #send has any serious performance penalty in Opal/JS?

**Comment by jgaskins** [comment]
There is [minor overhead](https://github.com/opal/opal/blob/ea7f3a5f9b5304658bd8b58b85cf13f455d37b5c/opal/corelib/basic_object.rb#L19-L29) to ensure the method exists, but it's trivial compared to the work that the `tag` call incurs. You should be good there.

**Comment by balmoral** [comment]
Thanks. Will close the issue.

**Comment by jgaskins** [comment]
Admittedly, the documentation is poor there. I like to think I'm a pretty good software developer, but I freely admit I'm really bad at doc writing. :-)

**Comment by balmoral** [comment]
I share your feelings about documentation. Expect/hope others will do it and do it well, but procrastinate forever on my own account!

Luckily for us your code is extremely easy to read and understand! Well-structured, concise and clean.

BTW/FWIW - I'd actually be happy having one entry point (#tag) for creating a component, rather than cluttering the class/module namespace with all the HTML tags. I now need to consider that #div and #tag do not accept the same arguments, and not to use #tag without passing all three arguments. Not a big problem, but I'm sure it will bite me again given my short term memory. :-)

**Comment by jgaskins** [comment]
> Luckily for us your code is extremely easy to read and understand! Well-structured, concise and clean.

😍 This is a _fantastic_ compliment!

>  I'd actually be happy having one entry point (#tag) for creating a component, rather than cluttering the class/module namespace with all the HTML tags.

You mean like _only_ doing `tag(:div, stuff)`? I think that's kinda cool, tbh (and it's how `virtual-dom` works), but I really like the shorthand. :-) You could make your own mixin for your components:

```ruby
module MyComponentMixin
  attr_accessor :router, :outlet # required for routing targets

  def tag(tag_name, attributes=nil, content=nil)
    %x{
      if(!(attributes === nil || attributes.$$is_hash)) {
        content = attributes;
        attributes = nil;
      }
    }

    # It's also a pure module function, so you can call it on the module itself
    Clearwater::Component.tag(tag_name, attributes, content)
  end
end
```

Since Clearwater really only depends on `render` for components that aren't acting as routing targets as well as `router=` and `outlet=` for components that are, this should be enough to make that work. :-)

> I now need to consider that #div and #tag do not accept the same arguments

Yeah, that was a hard decision for that reason. :-( I _loved_ that the tag methods were all just specific cases of `tag`. The methods themselves could actually be thought of as curried functions if you're into FP:

```ruby
tag = proc do |name, attrs, content|
  attrs = attrs.to_h.map { |k,v| " #{k}=#{v.inspect}"}.join
  "<#{name}#{attrs}>#{content}</#{name}>"
end
div = tag.curry[:div]
span = tag.curry[:span]

div[{class: 'foo'}, span[nil, 'hi']]
# => "<div class=\"foo\"><span>hi</span></div>"
```

I haven't tried this in Opal but it works on MRI :-)

The only reasons I went ahead with the change were because `tag` occupied the top slot of all of the performance-profiling runs I did (making it the most expensive function in terms of CPU time) and it was still an obscure enough method (I hadn't talked about it much at the time) that it was unlikely to hurt anyone's code at the time.

**Comment by balmoral** [comment]
I'll throw this one at you just so you know where I'm coming from/heading to:

```
      # def html(**args) ...
      #
      # Keyword args may contain any valid html element attribute (name and value).
      #
      # They may/will likely also contain one or more key-value pairs:
      #   :tag        => valid html tag
      #   :content => vdom node or array of nodes
      #   :on          => hash of event handlers, e.g. { click: ->{...}, change: ->{...} }
      #
      # Events may also be directly specified in args as (for example):
      #   :onclick => method(:button_clicked)
      #
      # Example:
      #
      #  html(
      #    tag: :div,
      #    class: 'md-form',
      #    content: [
      #      html(
      #        tag: :input,
      #        id: 'input1',
      #        type: 'text',
      #        class: 'form-control',
      #        on: {
      #          change: method(:input1_changed)
      #        }
      #       ),
      #      html(
      #        tag: :label,
      #        for: 'input1'
      #        content: 'Label for input 1'
      #      )
      #    ]
      #  )
```
What I like about key word arguments is that it's obvious what's going on. 

Is there a performance hit for kwargs?

**Comment by jgaskins** [comment]
> Is there a performance hit for kwargs?

There seems to be, but I don't know how much it will affect an app. The performance difference is VM-specific. The following benchmarks are iterations per second on macOS Sierra developer beta:

```
Chrome 54:
- Method call with positional args: 1,312,612
- Method call with keyword args: 1,244,354 (5.4% slower)

Chrome 57 (Canary):
- Method call with positional args: 1,066,492
- Method call with keyword args: 988,461 (7.9% slower)

Safari 10.0.2:
- Method call with positional args: 3,677,192
- Method call with keyword args: 2,230,674 (64.8% slower)

Safari Tech Preview 17:
- Method call with positional args: 2,815,590
- Method call with keyword args: 2,320,203 (21.4% slower)

Firefox 50:
- Method call with positional args: 1,483,562	
- Method call with keyword args: 900,848 (64.7% slower)
```

This being a microbenchmark, it doesn't mean it'll take 65% longer to render (also, the beta versions of the VMs are way slower, but I assume that's because they inject a lot of debugging code into the runtime). Only the segment of the entire rendering cycle involving this specific method boundary will take that much longer. So if the vdom-generation phase takes 30% of the render loop and 90% of it is cached (I don't factor in `CachedRender` in Clearwater itself so the worst-case scenario has less impact) and your internal processing of the args takes 2x as long as converting the , you can expect it to take around 2% longer to render.

However, if you take keyword arguments, because they're implemented via a hash (similarly to how MRI does it, I believe) the number of function signatures you generate is exactly 1: `html(Object)`. This means you shouldn't ever run into deoptimizations. :-)

I'd recommend experimenting with it in the Chrome profiler (seriously, the best client-side perf tool I've seen :-)) to see what it looks like on your machine.

**Comment by balmoral** [comment]
That's a great help. Thanks.
