### ISSUE TITLE
Fallback

### ISSUE THREAD

**Issue by arjunmenon** [clearwater-rb/clearwater#74]
Hey
Disabling javascript renders a blank page. Maybe a graceful fallback would be good UX.

**Comment by jgaskins** [comment]
Server-side rendering support does exist in Clearwater and I've published an [example Rails app](https://github.com/jgaskins/server_rendered_clearwater_example) showing how to use it. :-) Maybe I should link to it in the readme or at even add a wiki page to show how it's done.

Unfortunately, automating this within the gem itself is complicated since it requires integration with the server framework. I've been thinking of writing a `clearwater-rails` gem or something that handles this for Rails, at least, but I haven't gotten there yet. :-)

**Comment by jgaskins** [comment]
Gonna go ahead and close this for now. If some gems are published that integrate well with server-side frameworks, I'd be happy to re-open this for further discussion on how to support that integration from Clearwater's side. 👍
